--- 
apiVersion: v1
kind: Service
metadata: 
  name: cassandra
spec: 
  ports: 
    - name: cql
      port: 9042
      protocol: TCP
      targetPort: 9042
  selector: 
    app: kong-database

--- 
apiVersion: apps/v1alpha1
kind: PetSet
metadata: 
  name: kong-database
spec: 
  replicas: 3
  serviceName: cassandra
  template: 
    metadata: 
      annotations: 
        pod.alpha.kubernetes.io/initialized: "true"
      labels: 
        app: kong-database
    spec: 
      containers: 
        - env: 
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: CASSANDRA_AUTHORIZER
              value: "CassandraAuthorizer"
            - name: CASSANDRA_AUTHENTICATOR
              value: "PasswordAuthenticator"
            - name: CASSANDRA_AUTO_BOOTSTRAP
              value: "false"
            - name: CASSANDRA_SEED_PROVIDER
              value: "io.k8s.cassandra.KubernetesSeedProvider"
            - name: HEAP_NEWSIZE
              value: "100M"
            - name: POD_NAMESPACE
              valueFrom: 
                fieldRef: 
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom: 
                fieldRef: 
                  fieldPath: status.podIP
          resources: 
            limits: 
              cpu: 600m
          securityContext:
            runAsUser: 0
          name: cassandra
          image: containers.cisco.com/oneidentity/cassandra_ok:latest
          ports: 
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
          volumeMounts: 
            - mountPath: /cassandra_data
              name: data
      terminationGracePeriodSeconds: 0
  volumeClaimTemplates: 
    - metadata: 
        annotations: 
          volume.alpha.kubernetes.io/storage-class: anything
        name: data
      spec: 
        accessModes: 
          - ReadWriteMany
        resources: 
          requests: 
            storage: 2Gi
